### PR TITLE
utils: Guard LoadLibrary against dll preloading / hijacking attacks

### PR DESCRIPTION
**Pull request by learn-more**
See https://support.microsoft.com/en-us/help/2389418/secure-loading-of-libraries-to-prevent-dll-preloading-attacks for more info

### CODE REVIEW

**Comment by ColinFinck** [comment]
Thanks for your PRs, Mark! :)

Is there any advantage in using `LOAD_LIBRARY_SEARCH_SYSTEM32` when one has to implement the alternative code path for `LOAD_WITH_ALTERED_SEARCH_PATH` anyway?
And does `LoadLibraryExW` actually have any advantage over `LoadLibraryW`, where I could also specify a full path to the shcore.dll file?

**Comment by learn-more** [comment]
> `LOAD_LIBRARY_SEARCH_SYSTEM32`

`LOAD_LIBRARY_SEARCH_SYSTEM32 ` is also used for all static dependencies of the target dll, which are almost always specified using a relative path.
So if it is available, it is the safer approach.

**Comment by ColinFinck** [comment]
@learn-more I've made the coding style consistent with the rest and added some commits. Fine to merge that?

**Comment by learn-more** [comment]
Sure!

**Pull request merged**
